org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8 -Dhttp.socketTimeout=180000 -Dhttp.connectionTimeout=120000 -Dorg.gradle.internal.http.socketTimeout=180000 -Dorg.gradle.internal.http.connectionTimeout=120000 -Dorg.gradle.internal.repository.max.retries=10 -Dorg.gradle.internal.repository.initial.backoff=1000
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true

kotlin.code.style=official
